version: "3.9"

services:
  web:
    build: .
    image: static-website
    container_name: static-website
    expose:
      - "8080"
    depends_on:
      - api
  proxy:
    image: nginx:alpine
    container_name: web-proxy
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:8080
    depends_on:
      - web
